# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_auto_20180507_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='isxf',
            field=models.IntegerField(default=1),
        ),
    ]
