# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0003_goods_isxf'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='dealerid',
            field=models.CharField(default=' ', max_length=16),
        ),
        migrations.AddField(
            model_name='goods',
            name='pmdesc',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
