# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0005_auto_20180507_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtype',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
