# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0007_auto_20180507_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainShop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('trackid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'axf_shop',
            },
        ),
    ]
