# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0008_mainshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainshow',
            name='categoryid',
            field=models.CharField(default=' ', max_length=16),
        ),
    ]
