# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0009_mainshow_categoryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainshow',
            name='brandname',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
