# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0010_mainshow_brandname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainshow',
            name='childcid1',
            field=models.CharField(default=' ', max_length=16),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='childcid2',
            field=models.CharField(default=' ', max_length=16),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='childcid3',
            field=models.CharField(default=' ', max_length=16),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='productid1',
            field=models.CharField(default=' ', max_length=16),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='productid2',
            field=models.CharField(default=' ', max_length=16),
        ),
        migrations.AddField(
            model_name='mainshow',
            name='productid3',
            field=models.CharField(default=' ', max_length=16),
        ),
    ]
