# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0011_auto_20180507_1500'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodtype',
            table='axf_foodtypes',
        ),
    ]
