# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0012_auto_20180507_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='ticket',
            field=models.CharField(default=' ', max_length=64),
        ),
    ]
