# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0013_usermodel_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=255)),
                ('outtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'user_ticket',
            },
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='ticket',
        ),
        migrations.AddField(
            model_name='userticket',
            name='u',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='axf.UserModel'),
        ),
    ]
